JIS.Web/Models/CounsellingLetterHelper.cs
using iTextSharp.text;
using iTextSharp.text.html.simpleparser;
using iTextSharp.text.pdf;
using System;
using System.IO;
using System.Web;
using System.Web.UI;


namespace JIS.Web.Models
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;



    public class CounsellingLetterHelper
    {

        public static MemoryStream getCounselling(string Name, DateTime DOB, long CandidateId, string MobileNo, string Course,  DateTime CounsellingDate)
        {

            string reader = string.Empty;
            reader = GetHtmlTemplateOfCounselling();
            string s = reader.Replace("#MOBILENO#", MobileNo).Replace("#COUNSELLINGDATE#", string.Format("{0:dd/MMM/yyyy}", CounsellingDate)).Replace("#Name#", Name).Replace("#ApplicationNo#", CandidateId.ToString("D7")).Replace("#DOB#", DOB.ToString("dd/MM/yyyy")).Replace("#Course#", Course.Replace(",", " ,"));
            return CovertToPDF(s);
        }
        private static string GetHtmlTemplateOfCounselling()
        {
            string counsellingFormat = string.Empty;

            counsellingFormat = NetworkHelper.CallApiPoint(new ApiEndPoint().CounsellingLetterBaseUrl + "CL_WB_2021.html");
            return counsellingFormat;
        }
        public static MemoryStream CovertToPDF(string HTMLRawString)
        {
            if (string.IsNullOrEmpty(HTMLRawString)) return null;
            string FontPath = string.Empty;
            //FontPath = HttpRuntime.AppDomainAppPath + "\\Content\\fonts\\";
            StringWriter sw = new StringWriter();
            HtmlTextWriter hw = new HtmlTextWriter(sw);
            StringReader sr = new StringReader(HTMLRawString);
            //Document pdfDoc = new Document(PageSize.A4,
            Document pdfDoc = new Document(PageSize.A4, 20f, 20f, 20f, 20f);
            HTMLWorker htmlparser = new HTMLWorker(pdfDoc);
            MemoryStream stream = new MemoryStream();
            PdfWriter.GetInstance(pdfDoc, stream);
            pdfDoc.AddHeader("Header", "Counselling Letter");
            pdfDoc.Open();
            // step 4.1: register a unicode font and assign it an alliasF:\Working Project\JKSS\JKSS New\CCB2016\MissionAdmission\bootstrap\fonts\Nirmala.ttf
            //FontFactory.Register(FontPath + "kruti-dev-010.ttf", "nirmala");
            //FontFactory.Register(FontPath + "BijoyRegular.ttf", "vrinda");
            //FontFactory.Register(FontPath + "Nirmala.ttf", "nirmala");
            // step 4.2: create a style sheet and set the encoding to Identity-H
            iTextSharp.text.html.simpleparser.StyleSheet ST = new iTextSharp.text.html.simpleparser.StyleSheet();
            ST.LoadTagStyle("body", "encoding", "Identity-H");
            // step 4.3: assign the style sheet to the html parser
            htmlparser.SetStyleSheet(ST);
            htmlparser.Parse(sr);
            pdfDoc.Close();
            return stream;
        }
    }


}

JIS.Web/Controllers/DownloadController.cs
using JIS.Web.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace JIS.Web.Controllers
{
    public class DownloadController : Controller
    {
        DBContextJIS db = new DBContextJIS();

        // GET: Download
        public ActionResult Index()
        {
            //return RedirectToAction(nameof(LetterAsync), new { Id = 45 });
            return View();
        }
        public ActionResult CounsellingLetter()
        {
            LoadUI();
            return View();

        }
        [HttpPost]
        public ActionResult CounsellingLetter(ApplicationViewModel applicant)
        {
            bool IsRegistredCandidate = false;
            ApplicationModel candidateApplication = null;
            var dob = applicant.GetDOB();
            IsRegistredCandidate = this.db.Applications.OrderByDescending(x => x.RegDate).Any(
                 x =>
                 (x.MobileNo.Equals(applicant.Name) || x.Name.Equals(applicant.Name))
                 && DbFunctions.TruncateTime(x.DateOfBirth) == DbFunctions.TruncateTime(dob));


            if (IsRegistredCandidate)
            {
                candidateApplication =
                    this.db.Applications.OrderByDescending(x => x.RegDate).FirstOrDefault(
                        x =>
                        (x.MobileNo.Equals(applicant.Name) || x.Name.Equals(applicant.Name))
                        && DbFunctions.TruncateTime(x.DateOfBirth) == DbFunctions.TruncateTime(dob));
            }

            //if candidate is registred in system
            if (IsRegistredCandidate && candidateApplication != null)
            {

                   //
                    return RedirectToAction(nameof(LetterAsync), new { Id = candidateApplication.Id });


                    //this.ViewBag.Message = "झारखण्ड राज्य का काउंसलिंग लेटर संभवतः 15 जुलाई से डाउनलोड होगी, कृपया दिए गए दिनांक से काउंसलिंग लेटर डाउनलोड करने का प्रयास करें | अधिक जानकारी के लिए वेबसाइट देखते रहें या हेल्पलाइन नंबर पे कॉल करें | ";
     

            }
            else
            {
                this.ViewBag.Message = "OPPS! We dont found any registration details with your name 'or' mobile no. " + applicant.Name;
            }
            UI:
            LoadUI();
            return View(applicant);

        }

        public async Task<ActionResult> LetterAsync(int Id=0)
        {
            if (Id == 0)
            {
                return RedirectToAction(nameof(CounsellingLetter));
            }
            if (db.Applications.Any(x => x.Id == Id))
            {
                var Application = db.Applications.FirstOrDefault(x => x.Id == Id);
                ApplicationViewModel application = new ApplicationViewModel();
                application.Id = Application.Id;
                application.MobileNo = Application.MobileNo;
                application.Name = Application.Name;
                application.SelectedCourse = Application.Courses;
                application.DateOfBirth = Application.DateOfBirth;
                application.CounsellingDate = Application.CounsellingDate;

                MemoryStream stream = new MemoryStream();
                byte[] byteInfo = await PrepareCounsellingLetter(application);
                stream.Write(byteInfo, 0, byteInfo.Length);
                stream.Position = 0;
                return new FileStreamResult(stream, "application/pdf");
            }
            else
            {
               return RedirectToAction(nameof(CounsellingLetter));
            }

           
        }

        private void LoadUI()
        {
            ViewBag.DD = new SelectList(DateOfBirthHelper.DD(), "Value", "Text");
            ViewBag.MM = new SelectList(DateOfBirthHelper.MM(), "Value", "Text");
            ViewBag.YYYY = new SelectList(DateOfBirthHelper.YYYY(), "Value", "Text");
        }

        private async Task<byte[]> PrepareCounsellingLetter(ApplicationViewModel applicant)
        {



            //if candidate is registred in system
            if (applicant != null)
            {
                CounsellingLetterHelper clHelper = new CounsellingLetterHelper();
 
                //}



                #region CounsellingLetter

                MemoryStream stream = new MemoryStream();
                byte[] byteInfo =
                    CounsellingLetterHelper.getCounselling(
                        applicant.Name,
                        applicant.DateOfBirth,
                        applicant.Id,
                        applicant.MobileNo,
                        applicant.SelectedCourse,
                        applicant.CounsellingDate.Value
                        ).ToArray();// await this.CList()).ToArray();



                return byteInfo;


                #endregion
            }
            return null;
        }


    }
}

JIS.Web/Views/Download/CounsellingLetter.cshtml
@model JIS.Web.Models.ApplicationViewModel
@{
    ViewBag.Title = "Download Counselling Letter";
}

<div class="row justify-content-md-center">
    <div class="col-md-6">
        <div class="ml-3 mr-3 mt-5">
            <div class="card">
                <div class="card-header">
                    <h2>Download Your Counselling Letter</h2>



                </div>
                @*<div class="card-body">
            <h3>
                <ul>
                    <li>
                        Counselling Letter will be available on the website to download on or after @MvcApplication.getCounsellingLetterDownloadDate().

                    </li>
                </ul>
            </h3>
        </div>*@
                @*<div class="alert alert-success">
            Bihar & Other state candidate's (except Jharkhand) counselling letter available to download. For online counselling you need to pay <b>Rs. 300</b> as counselling fees.
        </div>*@

                @if (ViewBag.ErrorMessage != null)
                {
                    <div class="alert alert-danger">
                        @Html.Raw(ViewBag.ErrorMessage)
                    </div>
                }

                <hr />
                <div class="card-body">


                    @if (ViewBag.Message != null)
                    {
                        <div class="alert alert-danger">
                            @Html.Raw("<h3>" + ViewBag.Message.ToString() + "</h3>")
                        </div>
                    }
                    @if (TempData["Message"] != null)
                    {
                        <div class="alert alert-danger">
                            @Html.Raw("<h3>" + TempData["Message"].ToString() + "</h3>")
                        </div>
                    }

                    @using (Html.BeginForm("CounsellingLetter", "Download", FormMethod.Post, new { id = "frmDownloadCounselling" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-group">
                            <label class="control-label col-md-12" for="Name">Enter your registered mobile no.</label>
                            <div class="col-md-12">
                                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", Placeholder = "Enter your mobile no." } })
                                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.Label("Date of Birth", new { @class = "control-label col-md-12" })
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-4 col-xs-4 col-sm-4">
                                        @Html.DropDownList("DD", null, new { @class = "form-control" })


                                    </div>
                                    <div class="col-md-4 col-xs-4 col-sm-4">
                                        @Html.DropDownList("MM", null, new { @class = " form-control" })


                                    </div>
                                    <div class="col-md-4 col-xs-4 col-sm-4">
                                        @Html.DropDownList("YYYY", null, new { @class = "form-control" })


                                    </div>
                                    @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>
                        <div class="form-group text-center">
                            <br />
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>

                    }
                </div>



            </div>
        </div>
    </div>
</div>